#!/usr/bin/env bash
set -euo pipefail

ROOT=${ROOT:-/home/diana/fishing/blind_nav_rl}
BATCH_ROOT=${BATCH_ROOT:-$ROOT/runs/目标8显式脱困v10阶段3方案A保留线_v1002}
MANIFEST_PATH=${MANIFEST_PATH:-$BATCH_ROOT/批次参数.csv}
ARCHIVE_ROOT=${ARCHIVE_ROOT:-$ROOT/runs/目标8显式脱困v10阶段3方案A保留线_最终归档_v1002}
MIN_CHECKPOINT=${MIN_CHECKPOINT:-500}
EPISODES=${EPISODES:-20}
VIDEO_EPISODES=${VIDEO_EPISODES:-20}
DEVICE=${DEVICE:-cpu}
SCORE_PROFILE=${SCORE_PROFILE:-pressure_priority}

cd "$ROOT"
BATCH_ROOT="$BATCH_ROOT" \
MANIFEST_PATH="$MANIFEST_PATH" \
ARCHIVE_ROOT="$ARCHIVE_ROOT" \
MIN_CHECKPOINT="$MIN_CHECKPOINT" \
EPISODES="$EPISODES" \
VIDEO_EPISODES="$VIDEO_EPISODES" \
DEVICE="$DEVICE" \
SCORE_PROFILE="$SCORE_PROFILE" \
bash tools/归档_v10阶段3三方案对照_v1002.sh
